# NOTE: This file is auto generated by OpenAPI Generator 7.14.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PetStore.Model.Pet do
  @moduledoc """
  
  """
  use Ecto.Schema

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :name => String.t,
    :category => PetStore.Model.Category.t | nil,
    :photoUrls => [String.t],
    :tags => [PetStore.Model.Tag.t] | nil,
    :status => String.t | nil
  }

  @derive {JSON.Encoder, only: [:id, :name, :category, :photoUrls, :tags, :status]}
  @primary_key false
  embedded_schema do
    field :id, :integer
    field :name, :string
    embeds_one :category, PetStore.Model.Category
    field :photoUrls, {:array, :string}
    embeds_many :tags, PetStore.Model.Tag
    field :status, :string
  end

  @spec changeset(t(), map()) :: Ecto.Changeset.t()
  def changeset(%__MODULE__{} = struct, params) do
    struct
    |> Ecto.Changeset.cast(params, [:id, :name, :photoUrls, :status])
    |> Ecto.Changeset.validate_required([:name, :photoUrls])
    |> Ecto.Changeset.cast_embed(:category)
    |> Ecto.Changeset.cast_embed(:tags)
  end
end

